### ISSUE TITLE
project_init.sh:pip incompatibility issue

### ISSUE THREAD

**Issue by LakshmiSwethaGavini** [arjunptm/GITS#2] opened 2021-09-18 16:55 UTC
For python3 only users, getting this issue on running source ~/.bash_rc.
It might be because of the fact that Linux defaults to Python 2 or something incompatible with pathlib.
Traceback (most recent call last):
  File "gits_logging.py", line 3, in <module>
    from pathlib import Path
ImportError: No module named pathlib

**Comment by ramyasaimullapudi** [comment] 2021-09-18 16:56
I think the issue is with python and python3 confusion.
Some imports are python3 conpatible only, like pathlib

I am adding a new file for resolving the confusion

**Comment by ramyasaimullapudi** [comment] 2021-09-18 17:01
resolved this issue with PR#3

**Closed by ramyasaimullapudi** 2021-09-18 17:01 UTC
